# Directions
var NORTH = 0
var EAST  = 1
var SOUTH = 2
var WEST  = 3

var NEEDS_GRASS   = 15

# Tile Types
var TILE_GRASS    = 0
var TILE_WATER    = 1
var TILE_FOREST   = 2
var TILE_COASTN   = 3
var TILE_COASTE   = 4
var TILE_COASTS   = 5
var TILE_COASTW   = 6
var TILE_COASTNE  = 7
var TILE_COASTSE  = 8
var TILE_COASTSW  = 9
var TILE_COASTNW  = 10
var TILE_COASTNE2 = 11
var TILE_COASTSE2 = 12
var TILE_COASTSW2 = 13
var TILE_COASTNW2 = 14
var TILE_ROCKN    = 15
var TILE_ROCKE    = 16
var TILE_ROCKS    = 17
var TILE_ROCKW    = 18
var TILE_ROCKNE   = 19
var TILE_ROCKSE   = 20
var TILE_ROCKSW   = 21
var TILE_ROCKNW   = 22
var TILE_FORESTN   = 23
var TILE_FORESTE   = 24
var TILE_FORESTS   = 25
var TILE_FORESTW   = 26
var TILE_FORESTNE  = 27
var TILE_FORESTSE  = 28
var TILE_FORESTSW  = 29
var TILE_FORESTNW  = 30
var TILE_FORESTNE2 = 31
var TILE_FORESTSE2 = 32
var TILE_FORESTSW2 = 33
var TILE_FORESTNW2 = 34
var TILE_MINE      = 35

# Tile Edges
var GRASS    = 0
var WATER    = 1
var FOREST   = 2
var COAST_N  = 3
var COAST_E  = 4
var COAST_S  = 5
var COAST_W  = 6
var FOREST_N = 7
var FOREST_E = 8
var FOREST_S = 9
var FOREST_W = 10
var ROCK_N   = 11
var ROCK_E   = 12
var ROCK_S   = 13
var ROCK_W   = 14
var ROCK     = 15


# Dictionary of all tile types and tile edges, on the directions [North, East, South, West]
var tile_rules = {
	TILE_GRASS   : [GRASS, GRASS, GRASS, GRASS],
	TILE_WATER   : [WATER, WATER, WATER, WATER],
	TILE_FOREST  : [FOREST, FOREST, FOREST, FOREST],
	TILE_COASTN  : [GRASS, COAST_N, WATER, COAST_N],
	TILE_COASTE  : [COAST_E, GRASS, COAST_E, WATER],
	TILE_COASTS  : [WATER, COAST_S, GRASS, COAST_S],
	TILE_COASTW  : [COAST_W, WATER, COAST_W, GRASS],
	TILE_COASTNE : [GRASS, GRASS, COAST_E, COAST_N],
	TILE_COASTSE : [COAST_E, GRASS, GRASS, COAST_S],
	TILE_COASTSW : [COAST_W, COAST_S, GRASS, GRASS],
	TILE_COASTNW : [GRASS, COAST_N, COAST_W, GRASS],
	TILE_COASTNE2: [COAST_E, COAST_N, WATER, WATER],
	TILE_COASTSE2: [WATER, COAST_S, COAST_E, WATER],
	TILE_COASTSW2: [WATER, WATER, COAST_W, COAST_S],
	TILE_COASTNW2: [COAST_W, WATER, WATER, COAST_N],
	TILE_ROCKN   : [ROCK, ROCK_N, GRASS, ROCK_N],
	TILE_ROCKE   : [ROCK_E, ROCK, ROCK_E, GRASS],
	TILE_ROCKS   : [GRASS, ROCK_S, ROCK, ROCK_S],
	TILE_ROCKW   : [ROCK_W, GRASS, ROCK_W, ROCK],
	TILE_ROCKNE  : [ROCK_E, ROCK_N, GRASS, GRASS],
	TILE_ROCKSE  : [GRASS, ROCK_S, ROCK_E, GRASS],
	TILE_ROCKSW  : [GRASS, GRASS, ROCK_W, ROCK_S],
	TILE_ROCKNW  : [ROCK_W, GRASS, GRASS, ROCK_N],
	TILE_MINE    : [ROCK, ROCK_N, GRASS, ROCK_N],
	TILE_FORESTN : [FOREST, FOREST_N, GRASS, FOREST_N],
	TILE_FORESTE : [FOREST_E, FOREST, FOREST_E, GRASS],
	TILE_FORESTS : [GRASS, FOREST_S, FOREST, FOREST_S],
	TILE_FORESTW : [FOREST_W, GRASS, FOREST_W, FOREST],
	TILE_FORESTNE: [FOREST_E, FOREST_N, GRASS, GRASS],
	TILE_FORESTSE: [GRASS, FOREST_S, FOREST_E, GRASS],
	TILE_FORESTSW: [GRASS, GRASS, FOREST_W, FOREST_S],
	TILE_FORESTNW: [FOREST_W, GRASS, GRASS, FOREST_N],
	TILE_FORESTNE2: [FOREST, FOREST, FOREST_E, FOREST_N],
	TILE_FORESTSE2: [FOREST_E, FOREST, FOREST, FOREST_S],
	TILE_FORESTSW2: [FOREST_W, FOREST_S, FOREST, FOREST],
	TILE_FORESTNW2: [FOREST, FOREST_N, FOREST_W, FOREST],
}


var tile_weights = {
	TILE_GRASS    : 16,
	TILE_WATER    : 4,
	TILE_FOREST   : 5,
	TILE_COASTN   : 5,
	TILE_COASTE   : 5,
	TILE_COASTS   : 5,
	TILE_COASTW   : 5,
	TILE_COASTNE  : 5,
	TILE_COASTSE  : 5,
	TILE_COASTSW  : 5,
	TILE_COASTNW  : 5,
	TILE_COASTNE2 : 2,
	TILE_COASTSE2 : 2,
	TILE_COASTSW2 : 2,
	TILE_COASTNW2 : 2,
	TILE_FORESTN  : 4,
	TILE_FORESTE  : 4,
	TILE_FORESTS  : 4,
	TILE_FORESTW  : 4,
	TILE_FORESTNE : 4,
	TILE_FORESTSE : 4,
	TILE_FORESTSW : 4,
	TILE_FORESTNW : 4,
	TILE_FORESTNE2: 2,
	TILE_FORESTSE2: 2,
	TILE_FORESTSW2: 2,
	TILE_FORESTNW2: 2,
	TILE_ROCKN    : 4,
	TILE_ROCKE    : 4,
	TILE_ROCKS    : 4,
	TILE_ROCKW    : 4,
	TILE_ROCKNE   : 4,
	TILE_ROCKSE   : 4,
	TILE_ROCKSW   : 4,
	TILE_ROCKNW   : 4,
	TILE_MINE     : 1,
}


var tile_sprites = {
	TILE_GRASS : Vector2i(1, 0),
	TILE_WATER : Vector2i(8, 11),
	TILE_FOREST: Vector2i(1, 8),
	TILE_COASTN  : Vector2i(8, 10),
	TILE_COASTE  : Vector2i(9, 11),
	TILE_COASTS  : Vector2i(8, 12),
	TILE_COASTW  : Vector2i(7, 11),
	TILE_COASTNE : Vector2i(9, 10),
	TILE_COASTSE : Vector2i(9, 12),
	TILE_COASTSW : Vector2i(7, 12),
	TILE_COASTNW : Vector2i(7, 10),
	TILE_COASTNE2: Vector2i(11, 10),
	TILE_COASTSE2: Vector2i(11, 11),
	TILE_COASTSW2: Vector2i(10, 11),
	TILE_COASTNW2: Vector2i(10, 10),
	TILE_FORESTN  : Vector2i(1, 9),
	TILE_FORESTE  : Vector2i(0, 8),
	TILE_FORESTS  : Vector2i(1, 7),
	TILE_FORESTW  : Vector2i(2, 8),
	TILE_FORESTNE : Vector2i(0, 9),
	TILE_FORESTSE : Vector2i(0, 7),
	TILE_FORESTSW : Vector2i(2, 7),
	TILE_FORESTNW : Vector2i(2, 9),
	TILE_FORESTNE2: Vector2i(6, 8),
	TILE_FORESTSE2: Vector2i(6, 7),
	TILE_FORESTSW2: Vector2i(7, 7),
	TILE_FORESTNW2: Vector2i(7, 8),
	TILE_ROCKN   : Vector2i(12, 6),
	TILE_ROCKE   : Vector2i(11, 5),
	TILE_ROCKS   : Vector2i(12, 4),
	TILE_ROCKW   : Vector2i(13, 5),
	TILE_ROCKNE  : Vector2i(11, 6),
	TILE_ROCKSE  : Vector2i(11, 4),
	TILE_ROCKSW  : Vector2i(13, 4),
	TILE_ROCKNW  : Vector2i(13, 6),
	TILE_MINE    : Vector2i(19, 5),
}
